version: "3"
services:
  webserver:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - "db:pgsql-server"
    volumes:
      - ./target:/usr/local/tomcat/webapps
  db:
    image: postgres:9.6
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    tty: true
    ports:
      - 5050:80
    links:
      - "db:pgsql-server"
    depends_on:
      - db

volumes:
  dbdata:
    driver: local